# vim: set foldmethod=marker:
# [[plugins]]
# repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'Shougo/vimfiler.vim'
# on_cmd = ['VimFilerBufferDir', 'VimFilerCurrentDir']
depends = 'unite.vim'
[[plugins]]
repo = 'Konfekt/FastFold'
[[plugins]]
repo = 'LeafCage/foldCC.vim'
[[plugins]]
repo = 'LeafCage/yankround.vim'
[[plugins]]
repo = 'MarcWeber/vim-addon-mw-utils'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['unite.vim']
[[plugins]]
repo = 'Shougo/neossh.vim'
depends = ['unite.vim']
[[plugins]]
repo = 'Shougo/unite-outline'
depends = ['unite.vim']
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'Shougo/vimshell.vim'
depends = ['vimproc.vim']
[[plugins]]
repo = 'SirVer/ultisnips'
merged = 0
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'basyura/bitly.vim'
[[plugins]]
repo = 'cdmedia/itg_flat_vim'
[[plugins]]
repo = 'ciaranm/inkpot'
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'ervandew/supertab'
[[plugins]]
repo = 'gregsexton/MatchTag'
on_ft = ['html','xml']
[[plugins]]
repo = 'haya14busa/dein-command.vim'
[[plugins]]
repo = 'haya14busa/vim-migemo'
[[plugins]]
repo = 'haya14busa/vim-open-googletranslate'
[[plugins]]
repo = 'honza/vim-snippets'
[[plugins]]
repo = 'ishitaku5522/revimses'
rev = 'dev'
[[plugins]]
repo = 'istepura/vim-toolbar-icons-silk'
[[plugins]]
repo = 'joshdick/onedark.vim'
[[plugins]]
repo = 'junegunn/vim-easy-align'
# on_event = 'CursorMoved'
# [[plugins]]
# repo = 'justinmk/vim-dirvish'
# # on_event = 'VimEnter'
# # on_cmd = 'Dirvish'
[[plugins]]
repo = 'mattn/ctrlp-filer'
depends = 'ctrlp.vim'
[[plugins]]
repo = 'mattn/ctrlp-register'
depends = 'ctrlp.vim'
[[plugins]]
repo = 'mbbill/undotree'
# on_event = 'VimEnter'
# on_if = '!has('python')'
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
[[plugins]]
repo = 'osyo-manga/shabadou.vim'
[[plugins]]
repo = 'osyo-manga/vim-anzu'
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']
[[plugins]]
repo = 'rakr/vim-one'
[[plugins]]
repo = 'sickill/vim-monokai'
[[plugins]]
repo = 'superbrothers/vim-vimperator'
[[plugins]]
repo = 'terryma/vim-multiple-cursors'
[[plugins]]
repo = 'tmux-plugins/vim-tmux'
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'tomtom/tlib_vim'
[[plugins]]
repo = 'tpope/vim-dispatch'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'tpope/vim-surround'
# on_event = 'CursorMoved'
[[plugins]]
repo = 'tyru/caw.vim'
# on_event = 'CursorMoved'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'tyru/restart.vim'
[[plugins]]
repo = 'ujihisa/unite-colorscheme'
depends = ['unite.vim']
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
[[plugins]]
repo = 'vim-jp/vital.vim'
[[plugins]]
repo = 'vim-scripts/JavaScript-Indent'
on_ft = 'javascript'
[[plugins]]
repo = 'vim-scripts/pyte'
[[plugins]]
repo = 'vim-scripts/summerfruit256.vim'
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'yomi322/neco-tweetvim'
