# vim: set foldmethod=marker:

# Filer {{{
[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
# on_cmd = ['VimFilerBufferDir', 'VimFilerCurrentDir']

# [[plugins]]
# repo = 'cocopon/vaffle.vim'

# [[plugins]]
# repo = 'justinmk/vim-dirvish'
# on_event = 'VimEnter'
# on_cmd = 'Dirvish'

# }}}

# Shougo Ware {{{

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('python3')"
merged = 0

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['denite.nvim']

[[plugins]]
repo = 'Shougo/unite-outline'
depends = ['denite.nvim']

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"

# }}}

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'LeafCage/foldCC.vim'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'ervandew/supertab'

# Git{{{
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
# }}}

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'haya14busa/vim-open-googletranslate'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'ishitaku5522/revimses'
rev = 'dev'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'mattn/ctrlp-register'
depends = 'ctrlp.vim'

[[plugins]]
repo = 'mbbill/undotree'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

# [[plugins]]
# repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-surround'

# Comment Out{{{
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# [[plugins]]
# repo = 'tyru/caw.vim'
# }}}

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/restart.vim'

# [[plugins]]
# repo = 'ujihisa/unite-colorscheme'
# depends = ['denite.nvim']

[[plugins]]
repo = 'vim-airline/vim-airline'

# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'
# depends = 'vim-airline'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# [[plugins]]
# repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'vim-jp/autofmt'

# COLOR SCHEMES {{{
# [[plugins]]
# repo = 'altercation/vim-colors-solarized'

# [[plugins]]
# repo = 'vim-scripts/summerfruit256.vim'

# [[plugins]]
# repo = 'chriskempson/base16-vim'

# [[plugins]]
# repo = 'ciaranm/inkpot'

# [[plugins]]
# repo = 'flazz/vim-colorschemes'

# [[plugins]]
# repo = 'tomasr/molokai'

[[plugins]]
repo = 'joshdick/onedark.vim'

# [[plugins]]
# repo = 'rakr/vim-one'
# }}}

# QUICK RUN {{{
[[plugins]]
repo = "thinca/vim-quickrun"

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
depends = ['vim-quickrun']

[[plugins]]
repo = "osyo-manga/vim-watchdogs"
depends = ['vim-quickrun']
# }}}

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'aperezdc/vim-template'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'nixprime/cpsm'
merged = 0
