# deoplete completers
[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_cmd = 'Linediff' 

[[plugins]]
repo = 'Rip-Rip/clang_complete'
on_ft = ['c', 'cpp', 'h', 'hpp'] 
if = "has('nvim')"
depends = 'deoplete.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java' 

[[plugins]]
repo = 'basyura/bitly.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'bkad/CamelCaseMotion'
on_map = ['n', ',']
hook_post_source = ''' " {{{
  call g:plugin_mgr.lazy_hook('CamelCaseMotion')
''' # }}}


[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript'] 
if = "has('nvim')"
depends = 'deoplete.nvim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml' 

[[plugins]]
repo = 'chiel92/vim-autoformat'
on_cmd = 'Autoformat' 

[[plugins]]
repo = 'csscomb/vim-csscomb'
on_ft = 'css' 

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python'] 
if = "has('nvim')"
depends = 'deoplete.nvim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go'] 

[[plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoNew', 'MemoList'] 

[[plugins]]
repo = 'gregsexton/MatchTag'
on_ft = ['html','xml'] 

[[plugins]]
repo = 'haya14busa/vim-open-googletranslate'
on_cmd = 'OpenGoogleTranslate' 
depends = ['open-browser.vim']

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = 'markdown' 

[[plugins]]
repo = 'ishitaku5522/TweetVim'
on_cmd = ['TweetVimHomeTimeline', 'TweetVimUserStream', 'TweetVimSay', 'TweetVimCommandSay'] 
depends = ['vimproc.vim', 'bitly.vim', 'twibill.vim',  'open-browser.vim']

[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = 'Calendar' 

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown' 

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex' 

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarToggle', 'TagbarOpen'] 

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','xml'] 

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = ['UndotreeFocus', 'UndotreeHide', 'UndotreeShow', 'UndotreeToggle'] 

[[plugins]]
repo = 'mopp/next-alter.vim'
on_ft = ['c','cpp'] 

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['c','cpp'] 

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html' 

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript' 

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown' 

[[plugins]]
repo = 'rdnetto/YCM-Generator'
on_cmd = 'YcmGenerateConfig'
rev = 'stable' 

[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = ['OpenBrowser', 'OpenBrowserSearch', 'OpenBrowserSmartSearch']

[[plugins]]
repo = 'tyru/restart.vim'
on_cmd = 'Restart' 

[[plugins]]
repo = 'vim-jp/vital.vim'
on_cmd = 'Vitalize'

# [[plugins]]
# repo = 'zchee/deoplete-clang'
# on_ft = ['c', 'cpp', 'h', 'hpp'] 
# if = "has('nvim')"
# depends = 'deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']  
if = "has('nvim')"
depends = 'deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python'] 
if = "has('nvim')"
depends = 'deoplete.nvim'

