# vim:set foldmethod=marker:

[[plugins]]
repo = "bkad/CamelCaseMotion"
on_map = ['n', ',']
hook_post_source = ''' " {{{
  call g:plugin_mgr.lazy_hook('CamelCaseMotion')
''' # }}}

# [[plugins]]
# repo = "cohama/lexima.vim"
# on_event = "InsertEnter"
# hook_post_source = ''' " {{{
  # call g:plugin_mgr.lazy_hook('lexima.vim')
# ''' # }}}

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

# TweetVim {{{
[[plugins]]
repo = 'ishitaku5522/TweetVim'
on_cmd = ['TweetVimHomeTimeline', 'TweetVimUserStream', 'TweetVimSay', 'TweetVimCommandSay']
depends = ['bitly.vim', 'twibill.vim',  'open-browser.vim']

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'basyura/bitly.vim'
# }}}

# HTML CSS JS PLUGINS
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'csscomb/vim-csscomb'
on_ft = 'css'

[[plugins]]
repo = 'gregsexton/MatchTag'
on_ft = ['html','xml']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','xml']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoNew', 'MemoList']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# on_event = "CursorHold"
# depends = ['context_filetype.vim']

# [[plugins]]
# repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'rdnetto/YCM-Generator'
on_cmd = 'YcmGenerateConfig'
depends = "YouCompleteMe"

# [[plugins]]
# repo = 'chrisbra/csv.vim'
# on_ft = 'csv'

[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = 'Calendar'

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarToggle', 'TagbarOpen']

# [[plugins]]
# repo = 'yuratomo/gmail.vim'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_cmd = 'Linediff'

[[plugins]]
repo = "osyo-manga/vim-watchdogs"
on_event = ['BufWrite','CursorHold']
depends = ['vim-quickrun']
on_cmd = ['WatchdogsRun']
hook_post_source = ''' " {{{
  call g:plugin_mgr.lazy_hook('vim-watchdogs')
''' # }}}

[[plugins]]
repo = 'haya14busa/vim-open-googletranslate'
on_cmd = 'OpenGoogleTranslate'
depends = ['open-browser']

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = ['UndotreeFocus', 'UndotreeHide', 'UndotreeShow', 'UndotreeToggle']

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['c','cpp']

[[plugins]]
repo = 'mopp/next-alter.vim'
on_ft = ['c','cpp']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = [ 'OpenBrowser', 'OpenBrowserSearch', 'OpenBrowserSmartSearch' ]

[[plugins]]
repo = 'tyru/restart.vim'
on_cmd = 'Restart'

[[plugins]]
repo = 'chiel92/vim-autoformat'
on_cmd = 'Autoformat'
